from PIL import Image

monro=Image.open('monro.jpg')
red_monro,green_monro,blue_monro=monro.split()
coordinates_1=(50,0,696,522)
coordinates_2=(0,0,646,522)
coordinates_3=(25,0,671,522)
cr_red_monro_1=red_monro.crop(coordinates_1)
cr_red_monro_2=red_monro.crop(coordinates_3)
fnl_red_monro=Image.blend(cr_red_monro_1, cr_red_monro_2, 0.3)
cr_blue_monro_1=blue_monro.crop(coordinates_2)
cr_blue_monro_2=blue_monro.crop(coordinates_3)
fnl_blue_monro=Image.blend(cr_blue_monro_1, cr_blue_monro_2, 0.3)
fnl_green_monro=green_monro.crop(coordinates_3)
fnl_monro=Image.merge('RGB', (fnl_red_monro,fnl_green_monro,fnl_blue_monro))
fnl_monro.thumbnail((80, 80))
fnl_monro.save('fnl_monro.jpg')